# https://github.com/rhysd/actionlint/blob/main/docs/config.md
self-hosted-runner:
  labels:
    - deploy
    - Linux
    - X64
    - docker
    - self-hosted
    - dhis2-cert-staging-server
    - dhis2-cert-prod-server
