services:
  traefik:
    image: traefik:v3.6.6
    container_name: dhis2-cert-api-proxy
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443

      # Dashboard API listens on localhost inside the container; reach via SSH tunnel.
      - --entrypoints.traefik.address=127.0.0.1:8080
      - --api.dashboard=true

      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=http

      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true

      - --accesslog
      - --log
    networks:
      - traefik-public

volumes:
  traefik-certificates:

networks:
  traefik-public:
    external: true
